# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_report.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import * 
from PyQt5.QtGui import * 
from PyQt5.QtWidgets import * 

class Ui_Form_Report(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1260, 800)
        Form.setMinimumSize(QtCore.QSize(1260, 800))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CentralFrame = QtWidgets.QFrame(Form)
        self.CentralFrame.setStyleSheet("background-color: rgb(36, 40, 50);")
        self.CentralFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CentralFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CentralFrame.setObjectName("CentralFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.CentralFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.MoveFrame = QtWidgets.QFrame(self.CentralFrame)
        self.MoveFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MoveFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MoveFrame.setObjectName("MoveFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.MoveFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_Previous = QtWidgets.QPushButton(self.MoveFrame)
        self.btn_Previous.setMinimumSize(QtCore.QSize(35, 35))
        self.btn_Previous.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_Previous.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/24x24/icons/24x24/cil-arrow-circle-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Previous.setIcon(icon)
        self.btn_Previous.setIconSize(QtCore.QSize(24, 24))
        self.btn_Previous.setObjectName("btn_Previous")
        self.horizontalLayout_2.addWidget(self.btn_Previous)
        self.btn_Next = QtWidgets.QPushButton(self.MoveFrame)
        self.btn_Next.setMinimumSize(QtCore.QSize(35, 35))
        self.btn_Next.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_Next.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/24x24/icons/24x24/cil-arrow-circle-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Next.setIcon(icon1)
        self.btn_Next.setIconSize(QtCore.QSize(24, 24))
        self.btn_Next.setObjectName("btn_Next")
        self.horizontalLayout_2.addWidget(self.btn_Next)
        self.gridLayout.addWidget(self.MoveFrame, 0, 4, 1, 1, QtCore.Qt.AlignRight)
        self.label_TitleResult = QtWidgets.QLabel(self.CentralFrame)
        self.label_TitleResult.setMinimumSize(QtCore.QSize(0, 35))
        self.label_TitleResult.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_TitleResult.setFont(font)
        self.label_TitleResult.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_TitleResult.setObjectName("label_TitleResult")
        self.gridLayout.addWidget(self.label_TitleResult, 0, 0, 1, 1)
        self.Done = QtWidgets.QPushButton(self.CentralFrame)
        self.Done.setMinimumSize(QtCore.QSize(0, 25))
        self.Done.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Done.setObjectName("Done")
        self.gridLayout.addWidget(self.Done, 5, 4, 1, 1)
        self.label_Atelectasis = QtWidgets.QLabel(self.CentralFrame)
        self.label_Atelectasis.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(47, 53, 66);")
        self.label_Atelectasis.setObjectName("label_Atelectasis")
        self.gridLayout.addWidget(self.label_Atelectasis, 1, 2, 1, 1)
        self.label_ImgPluraleffusion = QtWidgets.QLabel(self.CentralFrame)
        self.label_ImgPluraleffusion.setMinimumSize(QtCore.QSize(250, 360))
        self.label_ImgPluraleffusion.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_ImgPluraleffusion.setStyleSheet("background-color: rgb(47, 53, 66);")
        self.label_ImgPluraleffusion.setText("")
        self.label_ImgPluraleffusion.setObjectName("label_ImgPluraleffusion")
        self.gridLayout.addWidget(self.label_ImgPluraleffusion, 2, 1, 1, 1)
        self.label_ImgBigheard = QtWidgets.QLabel(self.CentralFrame)
        self.label_ImgBigheard.setMinimumSize(QtCore.QSize(250, 360))
        self.label_ImgBigheard.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_ImgBigheard.setStyleSheet("background-color: rgb(47, 53, 66);")
        self.label_ImgBigheard.setText("")
        self.label_ImgBigheard.setObjectName("label_ImgBigheard")
        self.gridLayout.addWidget(self.label_ImgBigheard, 2, 3, 1, 1)
        self.label_BlurpointSymptom = QtWidgets.QLabel(self.CentralFrame)
        self.label_BlurpointSymptom.setMinimumSize(QtCore.QSize(0, 350))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_BlurpointSymptom.setFont(font)
        self.label_BlurpointSymptom.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(47, 53, 66);")
        self.label_BlurpointSymptom.setText("")
        self.label_BlurpointSymptom.setObjectName("label_BlurpointSymptom")
        self.label_BlurpointSymptom.setAlignment(Qt.AlignTop)
        self.gridLayout.addWidget(self.label_BlurpointSymptom, 4, 0, 1, 1)
        self.label_UndefinedObjectSymptom = QtWidgets.QLabel(self.CentralFrame)
        self.label_UndefinedObjectSymptom.setMinimumSize(QtCore.QSize(0, 350))
        self.label_UndefinedObjectSymptom.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_UndefinedObjectSymptom.setFont(font)
        self.label_UndefinedObjectSymptom.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(47, 53, 66);")
        self.label_UndefinedObjectSymptom.setText("")
        self.label_UndefinedObjectSymptom.setObjectName("label_UndefinedObjectSymptom")
        self.label_UndefinedObjectSymptom.setAlignment(Qt.AlignTop)
        self.gridLayout.addWidget(self.label_UndefinedObjectSymptom, 4, 4, 1, 1)
        self.label_AtelectasisSymptom = QtWidgets.QLabel(self.CentralFrame)
        self.label_AtelectasisSymptom.setMinimumSize(QtCore.QSize(0, 350))
        self.label_AtelectasisSymptom.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_AtelectasisSymptom.setFont(font)
        self.label_AtelectasisSymptom.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(47, 53, 66);")
        self.label_AtelectasisSymptom.setText("")
        self.label_AtelectasisSymptom.setObjectName("label_AtelectasisSymptom")
        self.label_AtelectasisSymptom.setAlignment(Qt.AlignTop)
        self.gridLayout.addWidget(self.label_AtelectasisSymptom, 4, 2, 1, 1)
        self.label_PluralEffusionSymptom = QtWidgets.QLabel(self.CentralFrame)
        self.label_PluralEffusionSymptom.setMinimumSize(QtCore.QSize(0, 350))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_PluralEffusionSymptom.setFont(font)
        self.label_PluralEffusionSymptom.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(47, 53, 66);")
        self.label_PluralEffusionSymptom.setText("")
        self.label_PluralEffusionSymptom.setObjectName("label_PluralEffusionSymptom")
        self.label_PluralEffusionSymptom.setAlignment(Qt.AlignTop)
        self.gridLayout.addWidget(self.label_PluralEffusionSymptom, 4, 1, 1, 1, QtCore.Qt.AlignTop)
        self.label_BigheardSymptom = QtWidgets.QLabel(self.CentralFrame)
        self.label_BigheardSymptom.setMinimumSize(QtCore.QSize(0, 350))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_BigheardSymptom.setFont(font)
        self.label_BigheardSymptom.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(47, 53, 66);")
        self.label_BigheardSymptom.setText("")
        self.label_BigheardSymptom.setObjectName("label_BigheardSymptom")
        self.label_BigheardSymptom.setAlignment(Qt.AlignTop)
        self.gridLayout.addWidget(self.label_BigheardSymptom, 4, 3, 1, 1, QtCore.Qt.AlignTop)
        self.label_imgBlurpoint = QtWidgets.QLabel(self.CentralFrame)
        self.label_imgBlurpoint.setMinimumSize(QtCore.QSize(250, 360))
        self.label_imgBlurpoint.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_imgBlurpoint.setStyleSheet("background-color: rgb(47, 53, 66);")
        self.label_imgBlurpoint.setText("")
        self.label_imgBlurpoint.setObjectName("label_imgBlurpoint")
        self.gridLayout.addWidget(self.label_imgBlurpoint, 2, 0, 1, 1)
        self.label_UndefinedObject = QtWidgets.QLabel(self.CentralFrame)
        self.label_UndefinedObject.setMinimumSize(QtCore.QSize(250, 360))
        self.label_UndefinedObject.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_UndefinedObject.setStyleSheet("background-color: rgb(47, 53, 66);")
        self.label_UndefinedObject.setText("")
        self.label_UndefinedObject.setObjectName("label_UndefinedObject")
        self.gridLayout.addWidget(self.label_UndefinedObject, 2, 4, 1, 1)
        self.label_Blurpoint = QtWidgets.QLabel(self.CentralFrame)
        self.label_Blurpoint.setMinimumSize(QtCore.QSize(0, 25))
        self.label_Blurpoint.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_Blurpoint.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"border: 1px solid rgb(47, 53, 66);")
        self.label_Blurpoint.setObjectName("label_Blurpoint")
        self.gridLayout.addWidget(self.label_Blurpoint, 1, 0, 1, 1)
        self.label_BigHeard = QtWidgets.QLabel(self.CentralFrame)
        self.label_BigHeard.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(47, 53, 66);")
        self.label_BigHeard.setObjectName("label_BigHeard")
        self.gridLayout.addWidget(self.label_BigHeard, 1, 3, 1, 1)
        self.label_PluralEffusion = QtWidgets.QLabel(self.CentralFrame)
        self.label_PluralEffusion.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(47, 53, 66);")
        self.label_PluralEffusion.setObjectName("label_PluralEffusion")
        self.gridLayout.addWidget(self.label_PluralEffusion, 1, 1, 1, 1)
        self.label_UndefinedObject_2 = QtWidgets.QLabel(self.CentralFrame)
        self.label_UndefinedObject_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(47, 53, 66);")
        self.label_UndefinedObject_2.setObjectName("label_UndefinedObject_2")
        self.gridLayout.addWidget(self.label_UndefinedObject_2, 1, 4, 1, 1)
        self.label_ImgAtelectasis = QtWidgets.QLabel(self.CentralFrame)
        self.label_ImgAtelectasis.setMinimumSize(QtCore.QSize(250, 360))
        self.label_ImgAtelectasis.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_ImgAtelectasis.setStyleSheet("background-color: rgb(47, 53, 66);\n"
"")
        self.label_ImgAtelectasis.setText("")
        self.label_ImgAtelectasis.setObjectName("label_ImgAtelectasis")
        self.gridLayout.addWidget(self.label_ImgAtelectasis, 2, 2, 1, 1)
        self.horizontalLayout.addWidget(self.CentralFrame)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_TitleResult.setText(_translate("Form", "RESULT"))
        self.Done.setText(_translate("Form", "OK"))
        self.label_Atelectasis.setText(_translate("Form", "Atelectasis"))
        self.label_Blurpoint.setText(_translate("Form", "BlurPoint"))
        self.label_BigHeard.setText(_translate("Form", "Big Heard"))
        self.label_PluralEffusion.setText(_translate("Form", "PluralEffusion"))
        self.label_UndefinedObject_2.setText(_translate("Form", "Undefined Object"))
import resource_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
